services:
  db:
    # 1. Instruct compose to build a customized layer instead of using a static image
    build:
      context: .
      dockerfile_inline: |
        FROM postgis/postgis:16-3.4
        RUN apt-get update && \
            apt-get install -y --no-install-recommends postgresql-16-pgvector && \
            rm -rf /var/lib/apt/lists/*
    container_name: handy_man_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-handy_man_db}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_EXPOSE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U ${DATABASE_USERNAME:-postgres} -d ${DATABASE_NAME:-handy_man_db}"
      ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: handy_man_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_HOSTNAME: db
      DATABASE_PORT: 5432
      PYTHONPATH: /app      # Force python to check the root directory for modules
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  user_app:
    build:
      context: ./frontend
      dockerfile: ./user_app/Dockerfile
      target: dev
      args:
        VITE_API_URL: ${PUBLIC_API_URL:-http://localhost:8000}
    container_name: handy_man_user_app
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${USER_APP_PROD_PORT:-5173}:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_USE_POLLING: "true"
      VITE_HMR_HOST: "0.0.0.0"
    volumes:
      - ./frontend:/app
      - /app/user_app/node_modules

volumes:
  postgres_data: