services:
  user_app:
    build:
      context: ./frontend
      dockerfile: ./user_app/Dockerfile
      target: dev
    environment:
      VITE_API_URL: ${PUBLIC_API_URL:-http://localhost:8000}
      VITE_PORT: 5173
      VITE_HMR_HOST: localhost
      VITE_HMR_CLIENT_PORT: 5173
      VITE_HMR_PROTOCOL: ws
      VITE_USE_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/user_app:/app/user_app
      - ./frontend/shared:/app/shared
      - user_node_modules:/app/user_app/node_modules
    ports:
      - "5173:5173"

volumes:
  user_node_modules:
