"""add_matched_count_and_interested_count_to_jobs

Revision ID: 0020e1503ca5
Revises: 86e44906ed03
Create Date: 2026-07-17 15:30:29.054427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0020e1503ca5'
down_revision: Union[str, Sequence[str], None] = '86e44906ed03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('matched_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('interested_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'interested_count')
    op.drop_column('jobs', 'matched_count')
    # ### end Alembic commands ###
