"""Add operating_radius and tags to Worker model

Revision ID: 0c4b23ef06b2
Revises: 7366d0e5468f
Create Date: 2026-06-02 17:26:41.436044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4b23ef06b2'
down_revision: Union[str, Sequence[str], None] = '7366d0e5468f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema safely with default values."""
    # Add columns as nullable first, or provide a server_default
    op.add_column('workers', sa.Column('operating_radius', sa.Float(), nullable=False, server_default='10.0'))
    op.add_column('workers', sa.Column('tags', sa.ARRAY(sa.String()), nullable=False, server_default='{}'))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'tags')
    op.drop_column('workers', 'operating_radius')
    # ### end Alembic commands ###
