"""fix_types_and_missing_columns

Revision ID: 24cc00094b4b
Revises: 50fe09d03459
Create Date: 2026-07-12 14:50:06.817859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24cc00094b4b'
down_revision: Union[str, Sequence[str], None] = '50fe09d03459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stage', sa.String(), server_default='interviewing', nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_rejected', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('pending_sub_skill', sa.Text(), nullable=True),
    sa.Column('pending_scenario', sa.Text(), nullable=True),
    sa.Column('has_verified_specialty', sa.Boolean(), nullable=True),
    sa.Column('scenario_score', sa.Integer(), nullable=True),
    sa.Column('scenario_passed', sa.Boolean(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_interview_sessions_id'), 'worker_interview_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.add_column('booking_chats', sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('booking_chats', 'history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_column('booking_chats', 'service_tags')
    op.drop_column('booking_chats', 'problem_category')
    op.drop_column('booking_chats', 'is_custom_category')
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('worker_chat_id', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('stage', sa.String(length=50), nullable=False))
    op.add_column('workers', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.add_column('workers', sa.Column('is_rejected', sa.Boolean(), nullable=False))
    op.add_column('workers', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('workers', sa.Column('job_category', sa.String(length=100), nullable=False))
    op.add_column('workers', sa.Column('category_tag', sa.String(length=100), nullable=False))
    op.add_column('workers', sa.Column('is_custom_category', sa.Boolean(), nullable=False))
    op.add_column('workers', sa.Column('specialities', postgresql.ARRAY(sa.String(length=100)), nullable=False))
    op.add_column('workers', sa.Column('specialized_tools_or_equipment', postgresql.ARRAY(sa.String(length=100)), nullable=False))
    op.add_column('workers', sa.Column('license_or_certification', sa.String(length=255), nullable=True))
    op.add_column('workers', sa.Column('job_description', sa.Text(), nullable=False))
    op.add_column('workers', sa.Column('emergency_available', sa.Boolean(), nullable=False))
    op.add_column('workers', sa.Column('has_verified_specialty', sa.Boolean(), nullable=False))
    op.add_column('workers', sa.Column('scenario_passed', sa.Boolean(), nullable=False))
    op.add_column('workers', sa.Column('scenario_score', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('description_vector', pgvector.sqlalchemy.vector.VECTOR(dim=4096), nullable=True))
    op.drop_geospatial_index(op.f('idx_workers_location'), table_name='workers', postgresql_using='gist', column_name='location')
    op.drop_index(op.f('ix_workers_category'), table_name='workers')
    op.drop_index(op.f('ix_workers_tags'), table_name='workers')
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_job_category'), 'workers', ['job_category'], unique=False)
    op.create_index(op.f('ix_workers_worker_chat_id'), 'workers', ['worker_chat_id'], unique=True)
    op.drop_constraint(op.f('workers_id_fkey'), 'workers', type_='foreignkey')
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workers', 'operating_radius')
    op.drop_column('workers', 'category')
    op.drop_column('workers', 'tags')
    op.drop_column('workers', 'additional_metadata')
    op.drop_geospatial_column('workers', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('workers', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('workers', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('operating_radius', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('workers_id_fkey'), 'workers', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workers_worker_chat_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_job_category'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.create_index(op.f('ix_workers_tags'), 'workers', ['tags'], unique=False)
    op.create_index(op.f('ix_workers_category'), 'workers', ['category'], unique=False)
    op.create_geospatial_index(op.f('idx_workers_location'), 'workers', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_column('workers', 'description_vector')
    op.drop_column('workers', 'scenario_score')
    op.drop_column('workers', 'scenario_passed')
    op.drop_column('workers', 'has_verified_specialty')
    op.drop_column('workers', 'emergency_available')
    op.drop_column('workers', 'job_description')
    op.drop_column('workers', 'license_or_certification')
    op.drop_column('workers', 'specialized_tools_or_equipment')
    op.drop_column('workers', 'specialities')
    op.drop_column('workers', 'is_custom_category')
    op.drop_column('workers', 'category_tag')
    op.drop_column('workers', 'job_category')
    op.drop_column('workers', 'rejection_reason')
    op.drop_column('workers', 'is_rejected')
    op.drop_column('workers', 'is_complete')
    op.drop_column('workers', 'stage')
    op.drop_column('workers', 'worker_chat_id')
    op.drop_column('workers', 'user_id')
    op.add_column('booking_chats', sa.Column('is_custom_category', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('booking_chats', sa.Column('problem_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('booking_chats', sa.Column('service_tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.alter_column('booking_chats', 'history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('booking_chats', 'categories')
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cust_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_desc', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('professional', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_index(op.f('ix_worker_interview_sessions_id'), table_name='worker_interview_sessions')
    op.drop_table('worker_interview_sessions')
    # ### end Alembic commands ###
