"""Added tables

Revision ID: 3f21b5424e02
Revises: cd8c01a88fb1
Create Date: 2026-05-30 19:43:15.756159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f21b5424e02'
down_revision: Union[str, Sequence[str], None] = 'cd8c01a88fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'SELECTED', 'REJECTED', name='bid_status_enum'), server_default='submitted', nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_id'), 'bids', ['id'], unique=False)
    op.create_table('chat_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_context', sa.String(), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    op.add_column('service_tasks', sa.Column('customer_id', sa.Uuid(), nullable=False))
    op.add_column('service_tasks', sa.Column('problem_description', sa.Text(), nullable=False))
    op.add_column('service_tasks', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('service_tasks', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.add_column('service_tasks', sa.Column('ai_extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('service_tasks', sa.Column('status', sa.Enum('OPEN', 'MATCHED', 'COMPLETED', name='job_status_enum'), server_default='open', nullable=False))
    op.alter_column('service_tasks', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_index('idx_service_tasks_location', 'service_tasks', ['location'], unique=False, postgresql_using='gist')
    op.drop_constraint(op.f('service_tasks_worker_id_fkey'), 'service_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'service_tasks', 'users', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('service_tasks', 'worker_id')
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_roles', 'id')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('workers', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.add_column('workers', sa.Column('ai_accessed_skills_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('workers', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.create_index('idx_workers_location', 'workers', ['location'], unique=False, postgresql_using='gist')
    op.drop_constraint(op.f('workers_user_id_fkey'), 'workers', type_='foreignkey')
    op.create_foreign_key(None, 'workers', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('workers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('workers_user_id_fkey'), 'workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_workers_location', table_name='workers', postgresql_using='gist')
    op.alter_column('workers', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('workers', 'ai_accessed_skills_json')
    op.drop_column('workers', 'location')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('user_roles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('service_tasks', sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('service_tasks_worker_id_fkey'), 'service_tasks', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_service_tasks_location', table_name='service_tasks', postgresql_using='gist')
    op.alter_column('service_tasks', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('service_tasks', 'status')
    op.drop_column('service_tasks', 'ai_extracted_json')
    op.drop_column('service_tasks', 'location')
    op.drop_column('service_tasks', 'image_url')
    op.drop_column('service_tasks', 'problem_description')
    op.drop_column('service_tasks', 'customer_id')
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.drop_index(op.f('ix_bids_id'), table_name='bids')
    op.drop_table('bids')
    # ### end Alembic commands ###
