"""added customer chat data

Revision ID: 50fe09d03459
Revises: cf5b90d465ce
Create Date: 2026-07-04 20:06:09.337912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50fe09d03459'
down_revision: Union[str, Sequence[str], None] = 'cf5b90d465ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_interview_sessions_id'), table_name='worker_interview_sessions')
    op.drop_table('worker_interview_sessions')
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_context', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-07-04 13:43:40.823787+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], name=op.f('chat_logs_task_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_logs_pkey'))
    )
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    op.create_table('worker_interview_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('stage', sa.VARCHAR(), server_default=sa.text("'interviewing'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_rejected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pending_sub_skill', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pending_scenario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('has_verified_specialty', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scenario_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scenario_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('worker_interview_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_interview_sessions_pkey'))
    )
    op.create_index(op.f('ix_worker_interview_sessions_id'), 'worker_interview_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
