"""add stage and rejection reason to worker skills table

Revision ID: 51d7d30a9ffb
Revises: f1a7c3d92b40
Create Date: 2026-08-02 11:42:37.352589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '51d7d30a9ffb'
down_revision: Union[str, Sequence[str], None] = 'f1a7c3d92b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'worker_skills', 
        sa.Column('stage', sa.String(length=50), server_default='pending_admin_review', nullable=False)
    )
    op.add_column('worker_skills', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_skills', 'rejection_reason')
    op.drop_column('worker_skills', 'stage')
    # ### end Alembic commands ###
