"""managed the columns for workers

Revision ID: 5b37002083f1
Revises: cf331e955c10
Create Date: 2026-06-11 21:43:00.265488

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b37002083f1"
down_revision: Union[str, Sequence[str], None] = "cf331e955c10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # We comment this out because 'speciality' does not exist in the local DB.
    op.drop_column("workers", "speciality")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workers",
        sa.Column(
            "speciality",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
