# """update_matching_and_job_status

# Revision ID: 7c429110e286
# Revises: 86e44906ed03
# Create Date: 2026-07-17 08:07:28.826036

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# import pgvector.sqlalchemy


# # revision identifiers, used by Alembic.
# revision: str = '7c429110e286'
# down_revision: Union[str, Sequence[str], None] = '86e44906ed03'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('job_worker_matches',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('job_id', sa.Integer(), nullable=False),
#     sa.Column('worker_id', sa.Integer(), nullable=False),
#     sa.Column('match_score', sa.Float(), nullable=False),
#     sa.Column('match_rank', sa.Integer(), nullable=False),
#     sa.Column('semantic_distance', sa.Float(), nullable=False),
#     sa.Column('is_active', sa.Boolean(), nullable=False),
#     sa.Column('is_interested', sa.Boolean(), nullable=False),
#     sa.Column('bid_amount', sa.Float(), nullable=True),
#     sa.Column('bid_message', sa.Text(), nullable=True),
#     sa.Column('is_selected', sa.Boolean(), nullable=False),
#     sa.Column('is_rejected', sa.Boolean(), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_job_worker_matches_id'), 'job_worker_matches', ['id'], unique=False)
#     op.create_index(op.f('ix_job_worker_matches_job_id'), 'job_worker_matches', ['job_id'], unique=False)
#     op.create_index(op.f('ix_job_worker_matches_worker_id'), 'job_worker_matches', ['worker_id'], unique=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_job_worker_matches_worker_id'), table_name='job_worker_matches')
#     op.drop_index(op.f('ix_job_worker_matches_job_id'), table_name='job_worker_matches')
#     op.drop_index(op.f('ix_job_worker_matches_id'), table_name='job_worker_matches')
#     op.drop_table('job_worker_matches')
#     # ### end Alembic commands ###
