"""Added Table for customer chat

Revision ID: 851060d28cd1
Revises: 8c460a8f35f6
Create Date: 2026-06-21 17:50:43.078476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '851060d28cd1'
down_revision: Union[str, Sequence[str], None] = '8c460a8f35f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_job_request', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('is_custom_category', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('problem_category', sa.String(), nullable=True),
    sa.Column('service_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_chats_id'), 'booking_chats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_chats_id'), table_name='booking_chats')
    op.drop_table('booking_chats')
    # ### end Alembic commands ###
