"""Added columns address and number for both worker and customer 

Revision ID: 86e44906ed03
Revises: ee0424fbcaff
Create Date: 2026-07-15 22:00:19.155251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '86e44906ed03'
down_revision: Union[str, Sequence[str], None] = 'ee0424fbcaff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('address_text', sa.Text(), nullable=True))
    op.add_column('workers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('workers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'longitude')
    op.drop_column('workers', 'latitude')
    op.drop_column('workers', 'address_text')
    op.drop_column('workers', 'phone_number')
    # ### end Alembic commands ###
