"""added user first and last name

Revision ID: 8c460a8f35f6
Revises: 5b37002083f1
Create Date: 2026-06-20 13:29:19.110151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c460a8f35f6'
down_revision: Union[str, Sequence[str], None] = '5b37002083f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add your new fields safely
    op.add_column('users', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(), nullable=True))
    
    # 2. Recreate the enum safely by catching the duplicate error if it exists
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bid_status_enum') THEN
                CREATE TYPE bid_status_enum AS ENUM ('SUBMITTED', 'SELECTED', 'REJECTED');
            END IF;
        END $$;
    """)
    
    # 3. Cast the column safely via raw SQL execution
    op.execute("""
        ALTER TABLE bids ALTER COLUMN status TYPE bid_status_enum 
        USING CASE 
          WHEN status::text = 'OPEN' THEN 'SUBMITTED'::bid_status_enum 
          WHEN status::text = 'MATCHED' THEN 'SELECTED'::bid_status_enum 
          WHEN status::text = 'COMPLETED' THEN 'REJECTED'::bid_status_enum
          ELSE 'SUBMITTED'::bid_status_enum 
        END
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.alter_column('bids', 'status',
               existing_type=sa.Enum('SUBMITTED', 'SELECTED', 'REJECTED', name='bid_status_enum'),
               type_=postgresql.ENUM('OPEN', 'MATCHED', 'COMPLETED', name='job_status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
