"""fix_types_and_missing_columns

Revision ID: a36518ac848e
Revises: 24cc00094b4b
Create Date: 2026-07-13 07:11:55.065953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a36518ac848e'
down_revision: Union[str, Sequence[str], None] = '24cc00094b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_chat_data', sa.Column('job_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_chat_data', 'job_title')
    # ### end Alembic commands ###
