"""add scheduled_date to jobs

Revision ID: ba288dc72e9b
Revises: 51d7d30a9ffb
Create Date: 2026-08-06 21:03:27.968351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba288dc72e9b'
down_revision: Union[str, Sequence[str], None] = '51d7d30a9ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_id_offsets')
    op.add_column('jobs', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_jobs_categories_gin'), table_name='jobs', postgresql_ops={'categories': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_jobs_open_requests'), table_name='jobs', postgresql_where='(is_job_request AND (worker_id IS NULL))')
    op.add_column('worker_skills', sa.Column('certificate', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('worker_skills', sa.Column('license', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('worker_skills', sa.Column('misc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('worker_skills', sa.Column('is_license', sa.Boolean(), nullable=True))
    op.add_column('worker_skills', sa.Column('is_certificate', sa.Boolean(), nullable=True))
    op.add_column('worker_skills', sa.Column('is_training', sa.Boolean(), nullable=True))
    op.drop_index(op.f('idx_workers_matchable'), table_name='workers', postgresql_where='(is_complete AND scenario_passed AND (NOT is_rejected))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workers_matchable'), 'workers', ['category_tag'], unique=False, postgresql_where='(is_complete AND scenario_passed AND (NOT is_rejected))')
    op.drop_column('worker_skills', 'is_training')
    op.drop_column('worker_skills', 'is_certificate')
    op.drop_column('worker_skills', 'is_license')
    op.drop_column('worker_skills', 'misc')
    op.drop_column('worker_skills', 'license')
    op.drop_column('worker_skills', 'certificate')
    op.create_index(op.f('idx_jobs_open_requests'), 'jobs', ['status'], unique=False, postgresql_where='(is_job_request AND (worker_id IS NULL))')
    op.create_index(op.f('idx_jobs_categories_gin'), 'jobs', ['categories'], unique=False, postgresql_ops={'categories': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_column('jobs', 'scheduled_date')
    op.create_table('seed_id_offsets',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('seed_id_offsets_pkey'))
    )
    # ### end Alembic commands ###
