"""add_worker_columns

Revision ID: cf331e955c10
Revises: 0c4b23ef06b2
Create Date: 2026-06-11 21:07:03.944025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf331e955c10'
down_revision: Union[str, Sequence[str], None] = '0c4b23ef06b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('category', sa.String(), nullable=False))
    op.add_column('workers', sa.Column('years_experience', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.create_index(op.f('ix_workers_category'), 'workers', ['category'], unique=False)
    op.create_index(op.f('ix_workers_tags'), 'workers', ['tags'], unique=False)
    op.drop_column('workers', 'ai_accessed_skills_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('ai_accessed_skills_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workers_tags'), table_name='workers')
    op.drop_index(op.f('ix_workers_category'), table_name='workers')
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.drop_column('workers', 'additional_metadata')
    op.drop_column('workers', 'years_experience')
    op.drop_column('workers', 'category')
    # ### end Alembic commands ###
