"""edited some db tables

Revision ID: e37a941881b9
Revises: c6b01677d72c
Create Date: 2026-07-25 13:05:07.667502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e37a941881b9'
down_revision: Union[str, Sequence[str], None] = 'c6b01677d72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_expertises_id'), table_name='worker_expertises')
    op.drop_index(op.f('ix_worker_expertises_worker_id'), table_name='worker_expertises')
    op.drop_table('worker_expertises')
    op.drop_column('customer_chat_data', 'address')
    op.drop_column('customer_chat_data', 'phone_number')
    # 1. Prune orphan rows in job_worker_matches before adding FK constraint
    op.execute("DELETE FROM job_worker_matches WHERE job_id NOT IN (SELECT id FROM jobs)")

    # 2. Existing foreign key creation
    op.create_foreign_key(None, 'job_worker_matches', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workers', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_worker_matches', type_='foreignkey')
    op.add_column('customer_chat_data', sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customer_chat_data', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('worker_expertises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=4096), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('worker_expertises_worker_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('worker_expertises_pkey'))
    )
    op.create_index(op.f('ix_worker_expertises_worker_id'), 'worker_expertises', ['worker_id'], unique=False)
    op.create_index(op.f('ix_worker_expertises_id'), 'worker_expertises', ['id'], unique=False)
    # ### end Alembic commands ###
