"""Added columns for worker

Revision ID: ee0424fbcaff
Revises: a3e3b1deb73a
Create Date: 2026-07-15 10:51:05.520526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = 'ee0424fbcaff'
down_revision: Union[str, Sequence[str], None] = 'a3e3b1deb73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('workers', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.create_geospatial_index('idx_workers_location', 'workers', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_workers_location', table_name='workers', postgresql_using='gist', column_name='location')
    op.drop_geospatial_column('workers', 'location')
    # ### end Alembic commands ###
