"""Some modifications in model file

Revision ID: fb6a45d85c62
Revises: ba288dc72e9b
Create Date: 2026-08-07 20:32:00.725402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6a45d85c62'
down_revision: Union[str, Sequence[str], None] = 'ba288dc72e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_geospatial_column('users', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.create_geospatial_index('idx_users_location', 'users', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    
    # --- Data Patch: Backfill existing NULL entries to satisfy NOT NULL constraints ---
    op.execute("UPDATE worker_skills SET certificate = '{}' WHERE certificate IS NULL")
    op.execute("UPDATE worker_skills SET license = '{}' WHERE license IS NULL")
    op.execute("UPDATE worker_skills SET misc = '{}' WHERE misc IS NULL")
    op.execute("UPDATE worker_skills SET is_license = FALSE WHERE is_license IS NULL")
    op.execute("UPDATE worker_skills SET is_certificate = FALSE WHERE is_certificate IS NULL")
    op.execute("UPDATE worker_skills SET is_training = FALSE WHERE is_training IS NULL")
    
    # --- Apply Schema Alters ---
    op.alter_column('worker_skills', 'certificate',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('worker_skills', 'license',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('worker_skills', 'misc',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('worker_skills', 'is_license',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('worker_skills', 'is_certificate',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('worker_skills', 'is_training',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('worker_skills', 'is_training',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('worker_skills', 'is_certificate',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('worker_skills', 'is_license',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('worker_skills', 'misc',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('worker_skills', 'license',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('worker_skills', 'certificate',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_geospatial_index('idx_users_location', table_name='users', postgresql_using='gist', column_name='location')
    op.drop_geospatial_column('users', 'location')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'address_text')
    op.drop_column('users', 'contact_name')
    op.drop_column('users', 'contact_number')
    # ### end Alembic commands ###