name: Deploy to EC2

on:
  push:
    branches: ["main"] # Change to "master" if your default branch is named master

jobs:
  # Gate: Runs tests in ci.yml first before deploying
  run-ci:
    uses: ./.github/workflows/ci.yml

  # Deploy: Runs only if run-ci succeeds
  deploy-to-ec2:
    needs: run-ci
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and update container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Handy_Man
            git pull origin main
            docker compose down
            docker compose up --build -d
            docker image prune -f